"""Physical dynamics and observation contracts shared by the domains.

Observations condition on the post-transition state and simultaneous joint action.
Transition events needed for observation generation must therefore be encoded in
that state (for example Wumpus bump and scream flags). Sampling and likelihood
evaluation must implement the same probability kernel. Optional RNG arguments
isolate real-environment randomness from planning randomness.

Action availability may depend only on information known at the acting agent's
history. A hidden-state action mask leaks information even when it saves search
work. Domain rollout policies have the same information restriction.
"""

import abc
from typing import Any, Dict, Hashable, List, Optional

# Type Aliases for strict typing in downstream planners.
# States, Actions, and Observations should strictly be Hashable to allow for dictionary
# lookups in UCB algorithms and Q-value tracking.
State = Hashable
Action = Hashable
Observation = Hashable
AgentID = Hashable


class POMDPModel(abc.ABC):
    r"""
    Abstract base class defining the physical < I, S, A, T, O, R, \gamma > tuple.

    Any domain evaluated by the I-POMCP solver (e.g., Tiger, UAV, Wumpus)
    must inherit from this class and implement these exact mechanics.
    """

    # ------------------------------------------------------------------ #
    # Core Environment Dynamics
    # ------------------------------------------------------------------ #

    @abc.abstractmethod
    def get_initial_state(self, rng=None) -> State:
        """
        Samples an initial physical state $s_0$ from the prior distribution $P(S_0)$.
        """
        pass

    @abc.abstractmethod
    def sample_transition(
        self, state: State, joint_action: Dict[AgentID, Action], rng=None
    ) -> State:
        r"""
        Generative Transition Function: $s' \sim T(s, \vec{a})$.

        Args:
            state: The current physical state.
            joint_action: A dictionary mapping every AgentID to their chosen Action.

        Returns:
            The subsequent physical state $s'$.
        """
        pass

    def transition_distribution(self, state: State, joint_action: Dict[AgentID, Action]):
        """Enumerate finite (post-state, probability) support for exact conditioning.

        Sampling is not a substitute for this law. A domain without finite support
        must use a separately justified sampled filter; it cannot silently turn one
        random transition into a probability-one event. Current domains implement
        this method explicitly. The enumerated and sampled laws must agree.
        """
        raise NotImplementedError("This model does not provide finite transition support")

    @abc.abstractmethod
    def sample_observation(
        self, state: State, joint_action: Dict[AgentID, Action], agent_id: AgentID, rng=None
    ) -> Observation:
        r"""
        Generative Observation Function: $o_i \sim O_i(s', \vec{a})$.
        Used to generate hypothetical realities during the MCTS rollout.

        Args:
            state: The physical state *after* the transition ($s'$).
            joint_action: The joint action that was just executed ($\vec{a}$).
            agent_id: The specific agent receiving the observation.

        Returns:
            The generated observation $o_i$.
        """
        pass

    @abc.abstractmethod
    def get_observation_prob(
        self,
        observation: Observation,
        state: State,
        joint_action: Dict[AgentID, Action],
        agent_id: AgentID,
    ) -> float:
        r"""
        Evaluative Observation Probability: $P(o_i \mid s', \vec{a})$.
        Used strictly to re-weight beliefs during the Interactive Particle Filter (IPF) update.

        [ARCHITECTURAL MANDATE]: The mathematical distribution returned by this method
        MUST perfectly symmetrically match the distribution generated by `sample_observation`.
        """
        pass

    @abc.abstractmethod
    def get_reward(
        self,
        state: State,
        joint_action: Dict[AgentID, Action],
        next_state: State,
        agent_id: AgentID,
    ) -> float:
        """
        Reward Function: $R_i(s, \vec{a}, s')$.

        Args:
            state: The pre-transition state ($s$).
            joint_action: The joint action executed ($\vec{a}$).
            next_state: The post-transition state ($s'$).
            agent_id: The agent for whom the reward is calculated.
        """
        pass

    @abc.abstractmethod
    def is_terminal(self, state: State) -> bool:
        """
        Evaluates whether the given state represents the end of an episode.
        If True, the MCTS trajectory immediately truncates and returns 0.0 future value.
        """
        pass

    # ------------------------------------------------------------------ #
    # Action and Observation Space Enumerators
    # ------------------------------------------------------------------ #

    @abc.abstractmethod
    def get_all_actions(self, agent_id: AgentID) -> List[Action]:
        """
        Return the maximal/complete action space for *agent_id*.
        Must be implemented to prevent runtime instantiation errors.
        """
        pass

    @abc.abstractmethod
    def get_all_observations(self, agent_id: AgentID) -> List[Observation]:
        """
        Return the maximal/complete observation space for *agent_id*.
        Must be implemented to satisfy observation-enumerating baseline solvers (like RTS).
        """
        pass

    def get_legal_actions(self, state: State, agent_id: AgentID) -> List[Action]:
        """
        Return the dynamically available actions for *agent_id* given the current *state*.

        [ARCHITECTURAL MANDATE]: Override this in concrete domains where actions
        can be rendered invalid by state (e.g., blocked paths, empty ammo).
        By default, this falls back to `get_all_actions`, but proper implementation
        massively reduces MCTS branching factors and speeds up planning.
        """
        return self.get_all_actions(agent_id)

    def is_epoch_reset(self, action: Action, observation: Observation) -> bool:
        """Evaluates whether the given action and observation indicate an environment epoch reset.

        In episodic or resetting domains (such as Tiger), opening a door resets the underlying
        physical state and restarts the observation-gathering epoch. Overridden by domains with reset dynamics.
        """
        return False

    def sample_state_consistent_with_obs(
        self,
        action: Action,
        observation: Observation,
        agent_id: Optional[AgentID] = None,
        rng: Any = None,
    ) -> State:
        """Samples a physical state consistent with the post-transition observation.

        This is a heuristic proposal hook, not a general Bayesian posterior.
        The default draws the initial prior without conditioning on history.
        Domains needing correct deprivation recovery require an explicit filter;
        see docs/THEORY.md. Callers must not interpret this as exact conditioning.
        """
        return self.get_initial_state(rng=rng)

    def get_rollout_action(self, state: State, agent_id: AgentID) -> Action:
        """Choose a rollout action using the domain's fixed default policy.

        The default samples uniformly from actions. Overrides must not exploit
        hidden state: a rollout policy still represents a partially informed agent.
        This policy estimates leaf values at finite search budgets; it is not an
        assertion of optimality. Domains with no legal actions terminate before
        this hook is called.
        """
        import random

        return random.choice(self.get_legal_actions(state, agent_id))
