# Absolute Path: <project_root>/core/pomdp_model.py

"""
pomdp_model.py — Abstract interface for the Interactive POMDP physical environment.

DESIGN DECISION RECORD (Phase 1 Overhaul):
------------------------------------------
1. GENERATIVE SYMMETRY ENFORCEMENT:
   The interface strictly delineates `sample_observation` (generative, used in MCTS)
   from `get_observation_prob` (evaluative, used in IPF). This architectural boundary
   prevents researchers from injecting artificial smoothing noise into the generative
   step without identically updating the probability evaluator, which is the #1 cause
   of Interactive Particle Filter divergence.

2. DYNAMIC ACTION MASKING (`get_legal_actions`):
   Rather than penalizing illegal actions with -1000 rewards (which wastes UCB1
   exploration bandwidth), the engine requests dynamically valid actions based on
   the exact physical state. This shrinks the branching factor |A| -> |A_legal(s)|,
   instantly tightening the sample complexity bounds of the Monte Carlo search.

3. TYPE HINTING & JIT COMPATIBILITY:
   State, Action, and Observation are kept as abstract types. Concrete implementations
   should strictly utilize immutable structs (e.g., tuples, frozen dataclasses with
   `slots=True`) to prevent GC stalls and Python object instantiation overhead during
   the millions of calls executed by the generative fast-loop.
"""

import abc
from typing import Dict, List, Hashable, Any

# Type Aliases for strict typing in downstream planners.
# States, Actions, and Observations should strictly be Hashable to allow for dictionary
# lookups in UCB algorithms and Q-value tracking.
State = Hashable
Action = Hashable
Observation = Hashable
AgentID = Hashable


class POMDPModel(abc.ABC):
    r"""
    Abstract base class defining the physical < I, S, A, T, O, R, \gamma > tuple.

    Any domain evaluated by the I-POMCP solver (e.g., Tiger, UAV, Wumpus)
    must inherit from this class and implement these exact mechanics.
    """

    # ------------------------------------------------------------------ #
    # Core Environment Dynamics
    # ------------------------------------------------------------------ #

    @abc.abstractmethod
    def get_initial_state(self) -> State:
        """
        Samples an initial physical state $s_0$ from the prior distribution $P(S_0)$.
        """
        pass

    @abc.abstractmethod
    def sample_transition(self, state: State, joint_action: Dict[AgentID, Action]) -> State:
        r"""
        Generative Transition Function: $s' \sim T(s, \vec{a})$.

        Args:
            state: The current physical state.
            joint_action: A dictionary mapping every AgentID to their chosen Action.

        Returns:
            The subsequent physical state $s'$.
        """
        pass

    @abc.abstractmethod
    def sample_observation(self, state: State, joint_action: Dict[AgentID, Action],
                           agent_id: AgentID) -> Observation:
        r"""
        Generative Observation Function: $o_i \sim O_i(s', \vec{a})$.
        Used to generate hypothetical realities during the MCTS rollout.

        Args:
            state: The physical state *after* the transition ($s'$).
            joint_action: The joint action that was just executed ($\vec{a}$).
            agent_id: The specific agent receiving the observation.

        Returns:
            The generated observation $o_i$.
        """
        pass

    @abc.abstractmethod
    def get_observation_prob(self, observation: Observation, state: State,
                             joint_action: Dict[AgentID, Action], agent_id: AgentID) -> float:
        r"""
        Evaluative Observation Probability: $P(o_i \mid s', \vec{a})$.
        Used strictly to re-weight beliefs during the Interactive Particle Filter (IPF) update.

        [ARCHITECTURAL MANDATE]: The mathematical distribution returned by this method
        MUST perfectly symmetrically match the distribution generated by `sample_observation`.
        """
        pass

    @abc.abstractmethod
    def get_reward(self, state: State, joint_action: Dict[AgentID, Action],
                   next_state: State, agent_id: AgentID) -> float:
        """
        Reward Function: $R_i(s, \vec{a}, s')$.

        Args:
            state: The pre-transition state ($s$).
            joint_action: The joint action executed ($\vec{a}$).
            next_state: The post-transition state ($s'$).
            agent_id: The agent for whom the reward is calculated.
        """
        pass

    @abc.abstractmethod
    def is_terminal(self, state: State) -> bool:
        """
        Evaluates whether the given state represents the end of an episode.
        If True, the MCTS trajectory immediately truncates and returns 0.0 future value.
        """
        pass

    # ------------------------------------------------------------------ #
    # Action and Observation Space Enumerators
    # ------------------------------------------------------------------ #

    @abc.abstractmethod
    def get_all_actions(self, agent_id: AgentID) -> List[Action]:
        """
        Return the maximal/complete action space for *agent_id*.
        Must be implemented to prevent runtime instantiation errors.
        """
        pass

    @abc.abstractmethod
    def get_all_observations(self, agent_id: AgentID) -> List[Observation]:
        """
        Return the maximal/complete observation space for *agent_id*.
        Must be implemented to satisfy exact-branching baseline solvers (like RTS).
        """
        pass

    def get_legal_actions(self, state: State, agent_id: AgentID) -> List[Action]:
        """
        Return the dynamically available actions for *agent_id* given the current *state*.

        [ARCHITECTURAL MANDATE]: Override this in concrete domains where actions
        can be rendered invalid by state (e.g., blocked paths, empty ammo).
        By default, this falls back to `get_all_actions`, but proper implementation
        massively reduces MCTS branching factors and speeds up planning.
        """
        return self.get_all_actions(agent_id)